# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_quarto_test',
                'doc_host': 'https://jazon33y.github.io',
                'git_url': 'https://github.com/jazon33y/nbdev_quarto_test',
                'lib_path': 'nbdev_quarto_test'},
  'syms': {'nbdev_quarto_test.core': {'nbdev_quarto_test.core.foo': ('core.html#foo', 'nbdev_quarto_test/core.py')}}}
